spring:
datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://101.33.197.216:3306/njupt?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
  username: root
  password: 285637zq

  thymeleaf:
    cache: false


mybatis:
  mapper-locations: classpath:mybatis/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.example.parkingmanagesys
