spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: 1122
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false

mybatis:
  mapper-locations: classpath:mybatis/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.example.parkingmanagesys
